//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public string FeedbackTitle { get; set; }
        public string FeefbackContent { get; set; }
        public string FUserName { get; set; }
        public string FUserTel { get; set; }
        public string FUserqq { get; set; }
        public string Email { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Replies { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public bool IsLock { get; set; }
    }
}
