//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int MenusId { get; set; }
        public int MenusParentId { get; set; }
        public string MenusName { get; set; }
        public string MenusUrl { get; set; }
        public int MenusSortId { get; set; }
        public bool MenusStatus { get; set; }
        public string MenusIco { get; set; }
        public int MenusLevel { get; set; }
        public string MenusRemark { get; set; }
        public string exp1 { get; set; }
        public Nullable<int> exp2 { get; set; }
        public System.DateTime MenusAddTime { get; set; }
    }
}
