//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.ModelViews
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class CategoryView
    {
        [DisplayName("ID")]
        public int CategoryId { get; set; }
        [DisplayName("类别类型")]
        public string CategoryType { get; set; }
        public int CategoryTypeId { get; set; }
        [DisplayName("类别标题")]
        public string CategroyTitle { get; set; }
        [DisplayName("父分类ID")]
        public int ParentId { get; set; }
    }
}
